# Get config file "kubectl config view"
# By default this file is located in .kube in the user's home directory
# /root/.kube  (manifests file)

apiVersion: v1
kind: Config
clusters:
- name: dev-cluster
  cluster:
    server: https://1.2.3.4:6443 # In case the file isn't on local
    certificate-authority: /path/to/ca.crt

users:
- name: dev-user
  user:
    client-certificate: /path/to/dev-user.crt
    client-key: /path/to/dev-user.key

contexts:
- name: dev-user@dev-context
  context:
    cluster: dev-cluster
    user: dev-user

current-context: dev-context # default users while using "kubectl" commands
#------------------------------
# Quick way to chang the "current-context"
# kubectl config use-context dev-user2@dev-context
