# ConfigMap
apiVersion: v1
kind: ConfigMap 
metadata:
  name: my-config
data:
  ENV_VAR_1: "value1"
  ENV_VAR_2: "value2"

# Secret
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_USER: YWRtaW4=  # Base64 encoded "admin"
  DB_PASSWORD: U3VwZXJTZWNyZXQxMjM=  # Base64 encoded "SuperSecret123"
  # to encode > echo "SuperSecret123" | base64
  # To decode > echo "U3VwZXJTZWNyZXQxMjM=" | base64 --decode
  # When using the secret keys in Application. Kubernetes will automatically decodes it
  # No need to decoding it manually.

#------------------------------
# Example of using ConfigMap or Secret in a Pod

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busyboxE
      # Mapping  whole keys in the ConfigMap file
      envFrom:
        - configMapRef: # or secretMapRef
            name: my-config
      #or Mapping key by key
      env:
        - name: ENV_VAR_1
          valueFrom:
            configMapKeyRef: # or secretKeyRef
              name: my-config
              key: ENV_VAR_1
        - name: ENV_VAR_2
          valueFrom:
            configMapKeyRef: # or secretKeyRef
              name: my-config
              key: ENV_VAR_2
