# ConfigMap
apiVersion: v1
kind: ConfigMap 
metadata:
  name: my-config
data:
  ENV_VAR_1: "value1"
  ENV_VAR_2: "value2"

#_____________________________

# Secret
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_USER: YWRtaW4=  # Base64 encoded "admin"
  DB_PASSWORD: U3VwZXJTZWNyZXQxMjM=  # Base64 encoded "SuperSecret123"
  # to encode > echo "SuperSecret123" | base64
  # To decode > echo "U3VwZXJTZWNyZXQxMjM=" | base64 --decode
  # When using the secret keys in Application. Kubernetes will automatically decodes it
  # No need to decoding it manually.
