apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busyboxE
      # Mapping  whole keys in the ConfigMap file
      envFrom:
        - configMapRef: # or secretMapRef
            name: my-config
      #or Mapping key by key
      env:
        - name: ENV_VAR_1
          valueFrom:
            configMapKeyRef: # or secretKeyRef
              name: my-config
              key: ENV_VAR_1
        - name: ENV_VAR_2
          valueFrom:
            configMapKeyRef: # or secretKeyRef
              name: my-config
              key: ENV_VAR_2
