apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: custom-scheduler

# How to use this scheduler
# Add schedulerName: custom-scheduler inside pod > spec
# _______________
# Additionally,We can use ConfigMap to create Environment variables