# kubectl get serviceaccount
#ServiceAccount is an object that provides an identity for processes that run in a Pod. 
#It is used mainly for authentication to the Kubernetes API
#Use case example
#If your app running inside a pod needs to list pods or get secrets, the service account associated 
#with it must have permission to do so via RBAC.


#How to find serviceaccount used th the pod
# kubectl describe pod {name} | grep Mounts -A2
#Result eg. /var/run/secrets/kubernetens.io/serviceaccount
#There are 3 files in serviceaccount
# kubectl exec -it {pod} -- ls /var/run/secrets/kubernetens.io/serviceaccount
#Result eg. ca.crt namespace token


#How to create 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
# Or kubectl create serviceaccount my-service-account

#How to use
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: my-service-account