apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 80  # Internal service port (inside the cluster)
      targetPort: 5000 # The port **inside** the Pod
      nodePort: 30080  # External Port (Optional, auto-assigned if omitted)

#Note Any pod inside the cluster can access the service using http://flask-nodeport:80

# Example how to mapping service to a pod ------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: my-flask-app
        ports:
        - containerPort: 5000

# Example how to access the pod via service mapping -----------------------------------------------------
# https://<NODE-IP>:30080